/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailTemplatesIndexRouteImport } from './routes/email-templates/index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies/index'
import { Route as EmailTemplatesIdRouteImport } from './routes/email-templates/$id'
import { Route as AgenciesIdRouteImport } from './routes/agencies/$id'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesIndexRoute = EmailTemplatesIndexRouteImport.update({
  id: '/email-templates/',
  path: '/email-templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesIdRoute = EmailTemplatesIdRouteImport.update({
  id: '/email-templates/$id',
  path: '/email-templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesIdRoute = AgenciesIdRouteImport.update({
  id: '/agencies/$id',
  path: '/agencies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/email-templates/$id': typeof EmailTemplatesIdRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/email-templates/': typeof EmailTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/email-templates/$id': typeof EmailTemplatesIdRoute
  '/agencies': typeof AgenciesIndexRoute
  '/email-templates': typeof EmailTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/email-templates/$id': typeof EmailTemplatesIdRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/email-templates/': typeof EmailTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/applications'
    | '/dashboard'
    | '/integrations'
    | '/login'
    | '/staff'
    | '/agencies/$id'
    | '/email-templates/$id'
    | '/agencies/'
    | '/email-templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/applications'
    | '/dashboard'
    | '/integrations'
    | '/login'
    | '/staff'
    | '/agencies/$id'
    | '/email-templates/$id'
    | '/agencies'
    | '/email-templates'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/applications'
    | '/dashboard'
    | '/integrations'
    | '/login'
    | '/staff'
    | '/agencies/$id'
    | '/email-templates/$id'
    | '/agencies/'
    | '/email-templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  StaffRoute: typeof StaffRoute
  AgenciesIdRoute: typeof AgenciesIdRoute
  EmailTemplatesIdRoute: typeof EmailTemplatesIdRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
  EmailTemplatesIndexRoute: typeof EmailTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates/': {
      id: '/email-templates/'
      path: '/email-templates'
      fullPath: '/email-templates/'
      preLoaderRoute: typeof EmailTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates/$id': {
      id: '/email-templates/$id'
      path: '/email-templates/$id'
      fullPath: '/email-templates/$id'
      preLoaderRoute: typeof EmailTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies/$id': {
      id: '/agencies/$id'
      path: '/agencies/$id'
      fullPath: '/agencies/$id'
      preLoaderRoute: typeof AgenciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  StaffRoute: StaffRoute,
  AgenciesIdRoute: AgenciesIdRoute,
  EmailTemplatesIdRoute: EmailTemplatesIdRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
  EmailTemplatesIndexRoute: EmailTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
