/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as ModerationIndexRouteImport } from './routes/moderation/index'
import { Route as EmailTemplatesIndexRouteImport } from './routes/email-templates/index'
import { Route as AgenciesIndexRouteImport } from './routes/agencies/index'
import { Route as VendorsIdRouteImport } from './routes/vendors/$id'
import { Route as ModerationReviewsRouteImport } from './routes/moderation/reviews'
import { Route as EmailTemplatesTemplateNameRouteImport } from './routes/email-templates/$templateName'
import { Route as AgenciesIdRouteImport } from './routes/agencies/$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationIndexRoute = ModerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModerationRoute,
} as any)
const EmailTemplatesIndexRoute = EmailTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmailTemplatesRoute,
} as any)
const AgenciesIndexRoute = AgenciesIndexRouteImport.update({
  id: '/agencies/',
  path: '/agencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationReviewsRoute = ModerationReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ModerationRoute,
} as any)
const EmailTemplatesTemplateNameRoute =
  EmailTemplatesTemplateNameRouteImport.update({
    id: '/$templateName',
    path: '/$templateName',
    getParentRoute: () => EmailTemplatesRoute,
  } as any)
const AgenciesIdRoute = AgenciesIdRouteImport.update({
  id: '/agencies/$id',
  path: '/agencies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/email-templates': typeof EmailTemplatesRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRouteWithChildren
  '/staff': typeof StaffRoute
  '/users': typeof UsersRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/email-templates/$templateName': typeof EmailTemplatesTemplateNameRoute
  '/moderation/reviews': typeof ModerationReviewsRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/email-templates/': typeof EmailTemplatesIndexRoute
  '/moderation/': typeof ModerationIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/users': typeof UsersRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/email-templates/$templateName': typeof EmailTemplatesTemplateNameRoute
  '/moderation/reviews': typeof ModerationReviewsRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/agencies': typeof AgenciesIndexRoute
  '/email-templates': typeof EmailTemplatesIndexRoute
  '/moderation': typeof ModerationIndexRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/applications': typeof ApplicationsRoute
  '/dashboard': typeof DashboardRoute
  '/email-templates': typeof EmailTemplatesRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRouteWithChildren
  '/staff': typeof StaffRoute
  '/users': typeof UsersRoute
  '/agencies/$id': typeof AgenciesIdRoute
  '/email-templates/$templateName': typeof EmailTemplatesTemplateNameRoute
  '/moderation/reviews': typeof ModerationReviewsRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/agencies/': typeof AgenciesIndexRoute
  '/email-templates/': typeof EmailTemplatesIndexRoute
  '/moderation/': typeof ModerationIndexRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/applications'
    | '/dashboard'
    | '/email-templates'
    | '/integrations'
    | '/login'
    | '/moderation'
    | '/staff'
    | '/users'
    | '/agencies/$id'
    | '/email-templates/$templateName'
    | '/moderation/reviews'
    | '/vendors/$id'
    | '/agencies/'
    | '/email-templates/'
    | '/moderation/'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/applications'
    | '/dashboard'
    | '/integrations'
    | '/login'
    | '/staff'
    | '/users'
    | '/agencies/$id'
    | '/email-templates/$templateName'
    | '/moderation/reviews'
    | '/vendors/$id'
    | '/agencies'
    | '/email-templates'
    | '/moderation'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/applications'
    | '/dashboard'
    | '/email-templates'
    | '/integrations'
    | '/login'
    | '/moderation'
    | '/staff'
    | '/users'
    | '/agencies/$id'
    | '/email-templates/$templateName'
    | '/moderation/reviews'
    | '/vendors/$id'
    | '/agencies/'
    | '/email-templates/'
    | '/moderation/'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  EmailTemplatesRoute: typeof EmailTemplatesRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  ModerationRoute: typeof ModerationRouteWithChildren
  StaffRoute: typeof StaffRoute
  UsersRoute: typeof UsersRoute
  AgenciesIdRoute: typeof AgenciesIdRoute
  VendorsIdRoute: typeof VendorsIdRoute
  AgenciesIndexRoute: typeof AgenciesIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation/': {
      id: '/moderation/'
      path: '/'
      fullPath: '/moderation/'
      preLoaderRoute: typeof ModerationIndexRouteImport
      parentRoute: typeof ModerationRoute
    }
    '/email-templates/': {
      id: '/email-templates/'
      path: '/'
      fullPath: '/email-templates/'
      preLoaderRoute: typeof EmailTemplatesIndexRouteImport
      parentRoute: typeof EmailTemplatesRoute
    }
    '/agencies/': {
      id: '/agencies/'
      path: '/agencies'
      fullPath: '/agencies/'
      preLoaderRoute: typeof AgenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation/reviews': {
      id: '/moderation/reviews'
      path: '/reviews'
      fullPath: '/moderation/reviews'
      preLoaderRoute: typeof ModerationReviewsRouteImport
      parentRoute: typeof ModerationRoute
    }
    '/email-templates/$templateName': {
      id: '/email-templates/$templateName'
      path: '/$templateName'
      fullPath: '/email-templates/$templateName'
      preLoaderRoute: typeof EmailTemplatesTemplateNameRouteImport
      parentRoute: typeof EmailTemplatesRoute
    }
    '/agencies/$id': {
      id: '/agencies/$id'
      path: '/agencies/$id'
      fullPath: '/agencies/$id'
      preLoaderRoute: typeof AgenciesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmailTemplatesRouteChildren {
  EmailTemplatesTemplateNameRoute: typeof EmailTemplatesTemplateNameRoute
  EmailTemplatesIndexRoute: typeof EmailTemplatesIndexRoute
}

const EmailTemplatesRouteChildren: EmailTemplatesRouteChildren = {
  EmailTemplatesTemplateNameRoute: EmailTemplatesTemplateNameRoute,
  EmailTemplatesIndexRoute: EmailTemplatesIndexRoute,
}

const EmailTemplatesRouteWithChildren = EmailTemplatesRoute._addFileChildren(
  EmailTemplatesRouteChildren,
)

interface ModerationRouteChildren {
  ModerationReviewsRoute: typeof ModerationReviewsRoute
  ModerationIndexRoute: typeof ModerationIndexRoute
}

const ModerationRouteChildren: ModerationRouteChildren = {
  ModerationReviewsRoute: ModerationReviewsRoute,
  ModerationIndexRoute: ModerationIndexRoute,
}

const ModerationRouteWithChildren = ModerationRoute._addFileChildren(
  ModerationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  EmailTemplatesRoute: EmailTemplatesRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  ModerationRoute: ModerationRouteWithChildren,
  StaffRoute: StaffRoute,
  UsersRoute: UsersRoute,
  AgenciesIdRoute: AgenciesIdRoute,
  VendorsIdRoute: VendorsIdRoute,
  AgenciesIndexRoute: AgenciesIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
